/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaMercearia;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.*;

/**
 *
 * @author gabri
 */
public class JanelaPrincipal extends javax.swing.JFrame {
//Representa a barra de rolagem

    private static JScrollPane barraRolagem;

    //auxilia na trasinção de paineisLayout existentes
    private static JPanel trocaInf;

    //gerencia qual painel está visivel
    private static CardLayout paineisLayout;

    //Criando tabela hash que conterá todos os paineis criados
    private static HashMap<String, JPanel> paineis;

    public JanelaPrincipal() {
        initComponents();
        meuInit();
    }

    private void meuInit() {
        paineis = new HashMap<>();
        
        //Carregando arquivos do banco de dados
        FakeBD.carga();

        //Ocupando o frame com a barra de rolagem
        barraRolagem = new JScrollPane();
        this.setLayout(new BorderLayout());
        this.add(barraRolagem);

        //configurar o painel que receberá o painel feito para os usuários
        paineisLayout = new CardLayout();
        trocaInf = new JPanel(paineisLayout);

        //mostrando a informação 
        barraRolagem.setViewportView(trocaInf);

        //qual o primeiro painel deisejo mostrar pro usuário
       // trocaInf.add(new CompraGUI(), "Compras");
       // paineisLayout.show(trocaInf, "Compras");
        fazTransicao(new CompraGUI(), "compra");
       
    }

    public static void fazTransicao(JPanel novoPainel, String nome) {
        //quando o novoPainel é nulo, quer dizer que o usuário já interagiu com o painel
        //quando não é nulo, essa é a primeira interação d usuário com o painel
        
        if(novoPainel != null && !paineis.containsKey(nome)){
            //usuario nunca vizualizou com esse painel
            trocaInf.add(novoPainel, nome);
            paineis.put(nome, novoPainel);
        }
        
        paineisLayout.show(trocaInf, nome);

        //correção do tamanho da primeira barra de rolagem
        trocaInf.setPreferredSize(paineis.get(nome).getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FakeBD.atualizaArquivo();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
